Update deploy_records.yml

diff --git a/.github/workflows/deploy_records.yml b/.github/workflows/deploy_records.yml
--- a/.github/workflows/deploy_records.yml
+++ b/.github/workflows/deploy_records.yml
@@ -24,6 +24,13 @@ jobs:
     - name: Install dependencies
       run: npm install
 
+    - name: Verify JSON files existence
+      run: |
+        if [ ! -f "./verify_jsons.js" ]; then
+          echo "verify_jsons.js not found!"
+          exit 1
+        fi
+
     - name: Run verification script
       run: node verify_jsons.js
 
@@ -62,7 +69,12 @@ jobs:
           node-version: '22.4.1'
 
       - name: Verify content of the JSONs
-        run: node ./scripts/verify_jsons.js
+        run: |
+          if [ ! -f "./verify_jsons.js" ]; then
+            echo "verify_jsons.js not found!"
+            exit 1
+          fi
+          node ./verify_jsons.js
 
       - name: Install DNSControl
         run: |
